### ISSUE TITLE
Only Pulls PS4 compatible games

### ISSUE THREAD

**Issue by CMDRLucienn** [FriendsOfGalaxy/galaxy-integration-psn#1]
The integration seems to only pull PS4 compatible games. If a game is available on multiple consoles (PS3, PS Vita, PS4), it'll pull it, but only if the PS4 is one of the consoles it is available on. PS Vita and PS3 games, regardless of trophy support or physical/digital format, are excluded.

I suspect this is due to the assumption of Communication ID for the games. Only PS4 supports Sony's extended social network/communication features via the console.

Perhaps presence/absence of trophies might work as a better filter for whether a game is a game or DLC?

**Comment by CMDRLucienn** [comment]
Just realized; absence of trophies won't be perfect as some older games from PS3's very early life weren't required to have trophies. Those are very few and far between however.

**Comment by bmironer** [comment]
It seems the https://gamelist.api.playstation.com/v1/users/me/titles API returns only PS4 titles anyway.

**Comment by FriendsOfGalaxy** [comment]
Indeed, as @bmironer mentioned, PSN backend returns only PS4 games. We could use trophies and come up with some heuristic to determine owned games, but this would be quite inaccurate:
- some games do not have trophies at all, so will be missing
- others have "shared" trophies amongst several titlies, so it's not possible to determine which of them (or all of them) you own
- throphies names for some are completely different from game names, so really hard to map them to each other.

With all that, the best solution is to use a backend (or special flags) that returns PS/PS3/Vita games, but I'm not aware of such one :(

**Comment by bmironer** [comment]
The store API has all your 'entitlements', for all digital owned and ps+ games and DLCs, for all platforms, with extensive metadata. That wouldn't give you your disc / carts games though.
But do we want to display games you might have borrowed / resold or only the PSN ones?

**Comment by CMDRLucienn** [comment]
Some services such as Exophase use the trophies to great success:

- The games without trophies are very few in number now, pre-July 2008 release dated games (although most have had trophies patched in) and are already missing from the current API, so the trophy method would still be a huge improvement
- Shared trophies amongst several titles are only a thing (that I'm aware of) between different versions of the same title, so PSVita/PS3 versions share a list; collectors edition/regular edition share a list, Japanese/European releases sometimes share a list, etc. The current method has the same issue as its showing PSVita games that I've played but don't own a PS4 copy of via the API because a PS4 copy does exist on the store.
- I'm not sure about this one, I've not seen a trophy that cannot be directly linked to a game as of yet, but I'm not sure what trophy services use to map these out.

Another option, which won't grab all the physical titles but will grab a wider array of digital/PSN titles, could be something based off of PSDLE: https://repod.github.io/psdle/
It grabs the user's digital purchases from the regular old PSN website while the user is looking at their licenses, which should be doable within the authentication process.

As for possibly sold-on/no longer owned games, that is an issue with the current API too, since it returns physical games too. A number of games returned on the list I only own physically, and in some cases for another platform other than PS4, but if I had sold those on they'd still be there. I suppose Hiding the game in GOG could be a solution to this.

I agree though that there doesn't seem to be a perfect solution to this, unless a better API could be provided by Sony.

**Comment by PoppyWorks** [comment]
Raptr used to use a combination of trophy data and knowing if packets from PSN would coming and going on your network (I think?).

It'd be great to have PS3 and Vita games appear in these lists.

**Comment by Azekthi** [comment]
https://psnprofiles.com/ manages to grab PS3 and Vita trophy lists just fine. It'd be really great to see trophy information for these two platforms in this integration as well.

**Comment by FriendsOfGalaxy** [comment]
PS5 games are supported not. Not sure about PS3 /Vita
