### ISSUE TITLE
Unable to Sign-In 

### ISSUE THREAD

**Issue by MinusGabriel** [FriendsOfGalaxy/galaxy-integration-psn#12]
Signing into PSN via the plugin returns this message 

"A connection to the server could not be established.
(18.86eb7068.1589124594.41d420b7)"

I am on GOG 2.0.15.43 btw.

**Comment by ShaunV2** [comment]
@MinusGabriel You should go ahead and close this issue since it is a duplicate and you found the right issue to talk in.
