### ISSUE TITLE
PS5 games not being added to library and tracking earned trophies.

### ISSUE THREAD

**Issue by Kiznel** [FriendsOfGalaxy/galaxy-integration-psn#17]
Playing PS5 games doesn't add them to the GOG library, or track earned trophies in the activity feed. PS4 games are still added to the library as usual.

[Last earned trophies tracked by PSNprofiles.com](https://i.imgur.com/Ei8lofk.png)
[Last earned trophies tracked by GOG Galaxy](https://i.imgur.com/NVFmq3W.png)

**Expected behaviour**
PS5 games added to library and PS4/5 trophies earned on PS5 show in activity feed.

**Attached logs**
[plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/5618780/plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log)

**Comment by AwstenWhite** [comment]
Also having this issue. It almost seems like the latest release of galaxy-integration-psn isn't carrying over to the in-app integration menu of GOG Galaxy.

**Comment by tyrirn** [comment]
I also have a game that is missing from GoG
- FruitNinjaVR

[plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/6632906/plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log)

**Comment by FriendsOfGalaxy** [comment]
PS5 games should be added now. For trophies track #28
