### ISSUE TITLE
PSN Games show in Subscriptions section

### ISSUE THREAD

**Issue by ciaron88** [FriendsOfGalaxy/galaxy-integration-psn#18]
**Describe the bug**
Need for speed payback and Vampyr show in Subscriptions section

**Expected behavior**
Need for speed payback and Vampyr should NOT be in Subscriptions section as I OWN these games on PSN

**Comment by FriendsOfGalaxy** [comment]
hi @ciaron88 that is expected behavior if you have PS Plus enabled. Do you?

Does Need for speed and Vampyr show in your owned games on PSN as well?

**Comment by ciaron88** [comment]
Ahh, thanks found the setting to turn off the PS Plus subscription that got rid of them in the subscription section :) cheers

On a side note I have a lot more game on PS Plus (100+) that ONLY show in owned games and yes JUST Need for speed and Vampyr show in both owned and subscription. Don't know if this is an issue or not.

**Comment by FriendsOfGalaxy** [comment]
Yes, that is expected as well: only games from current month are shown as subscription games (public, store region dependent information). I have not found way to distinguish your owned games from those coming from PS Plus. But still there is some added value to shown current month PLUS games as a) they are new b) they can be activated in limited time.
