### ISSUE TITLE
Missing Games

### ISSUE THREAD

**Issue by psxdad** [FriendsOfGalaxy/galaxy-integration-psn#2]
Missing Uncharted: Lost Legacy for some reason

**Comment by Malus3** [comment]
I got the same problem : 
I can't see Spiderman, Uncharted Lost Legacy, Rocket League and some others, in spite of some other users have them in their library.

**Comment by inamo-dragon** [comment]
Same problem here. I am missing quite some games (especially PS3 and Vita) in the games overview. In the GOG forum there is discussion for this topic as well: https://www.gog.com/forum/general_beta_gog_galaxy_2.0/missing_ps4_games_from_playstation_network_integration

**Comment by ShaunV2** [comment]
The only issue I'm currently having at the moment is the fact it is unable to pull trophy data to Star Ocean First Departure R on PS4 ([PSN Profiles](https://psnprofiles.com/trophies/10083-star-ocean-first-departure-r/MegaManZXAvent) has it), it thinks there are no trophies when that is wrong, I have earned two trophies already but from what I've seen of other titles you don't have to earn any trophies or even play them for it to pull the trophy data to it just it being on your PSN account is enough.

**Comment by inamo-dragon** [comment]
It is slightly better with the version of the plugin of branflaker. The pull request for this here is open since October 19. But still lots of games are missing. Especially Vita only games or PSP/Vita games without trophies. But also PS3 games that do have trophies. So basically I like the idea of new Galaxy client, but IMO there should be more attention on the integration of other platforms. Maybe Sony's API is so poor, don't know.

**Comment by FriendsOfGalaxy** [comment]
@branflaker have you changed also a logic for finding PS4 games? ^

**Comment by branflaker** [comment]
My plugin doesn't change the logic for finding PS4 games.  I don't think it would help with Uncharted: Lost Legacy.

**Comment by Taramur** [comment]
I am missing some PSN games. Most games are disk versions like Bloodborne (DLC is showing), Shadow of the Tomb Raider, Marvel Spider Man. 

Digital, not disk: Dark Souls Remastered

But the logfiles show, that the integration wants to pull the trophys of these games. Strange.

**Comment by dotslash-baunthy** [comment]
The Last of Us Part 2 is missing. Initially I thought it the problem existed with games that were pre-ordered but it's not so. I can see Ghost Of Tsushima.

**Comment by ShaunV2** [comment]
I noticed a few days ago Trails of Mana isn't showing up on my library when it should be since I own it and have actually earned some trophies from it.

**Comment by V-Slash** [comment]
I am having the same issue with GoG Galaxy not showing Ghost of Tsushima in my Playstation library, yet it shows when I've played God of War or Persona 5 Royal just fine.

**Comment by dotslash-baunthy** [comment]
Here's what I did to fix it -
1. Log out
2. Delete app data (GOG.com)
3. Reinstall GOG Galaxy
No idea why it worked but the library now shows The Last Of Us Part 2.

**Comment by ShaunV2** [comment]
You shouldn't have to do that to fix it.

**Comment by HailAlistair** [comment]
For me it's The Last of Us Part II that doesn't show up. Others have the same problem: https://www.gog.com/forum/general_beta_gog_galaxy_2.0/the_last_of_us_part_ii_missing_from_library_playstation_network_community_integration/page1

**Comment by ShaunV2** [comment]
Still missing Trials of Mana and also missing The Legend of Heroes: Trails of Cold Steel IV, neither games can be detected even though I own both and have earned trophies on both.

**Comment by FriendsOfGalaxy** [comment]
@ShaunV2 please share your plugin logs

**Comment by ShaunV2** [comment]
> @ShaunV2 please share your plugin logs

I have no idea where to find those at or what file you're looking for.

**Comment by FriendsOfGalaxy** [comment]
@ShaunV2 there you go:  https://github.com/FriendsOfGalaxy/galaxy-integration-psn/wiki/Log-files

**Comment by ShaunV2** [comment]
[plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/5701899/plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log)

**Comment by FriendsOfGalaxy** [comment]
@ShaunV2 I see those game titles for trophy API but not for gamelist API. Can you share log.1 and log.2 logs?

**Comment by FriendsOfGalaxy** [comment]
You can also try this version: 
[psn_use_trophies_for_lacking_game_names.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/5703923/psn_use_trophies_for_lacking_game_names.zip)
- Close Galaxy
- go to `%localappdata%\GOG.com\Galaxy\plugins\installed`
- remove psn plugin
- unpack attached one (so the structure is "installed/psn_use_trophies_for_lacking_game_names/<bunch of file here>)
- run Galaxy and wait some time (plugin will drop cache and fetch everything again). Whatever version you use, please send log and log.1 files back.

**Comment by ShaunV2** [comment]
[logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/5706158/logs.zip)
I had to zip the 3 files as log.1 and log.2 files aren't supported to be uploaded here.

That version does work for both games but it seems to not able to pull the trophy data for Cold Steel IV.

**Comment by FriendsOfGalaxy** [comment]
Hi @ShaunV2 

Thanks you for testing!
looks like plugin returns achievements for that game. So that is probably problem of Galaxy. I hope temporal

```
2020-12-16 16:06:14,305 - galaxy.api.jsonrpc - INFO - Sending notification: method=game_achievements_import_success, params={'game_id': 'CUSA04726_00', 'unlocked_achievements': [Achievement(unlock_time=1482621202.0, achievement_id='NPWR10787_00_29', achievement_name='Chain Beginner'), Achievement(unlock_time=1482627545.0, achievement_id='NPWR10787_00_32', achievement_name='Variant Hunter')]
```

I'm releasing the new version for everyone.

**Comment by philou-felin** [comment]
Is it fixed?

**Comment by FriendsOfGalaxy** [comment]
Yea, some part of it (for PS4 games) should be fixed. I'm waiting for confirmation from @psxdad  @Malus3 @Taramur  @dotslash-baunthy 

is it fixed for you?

**Comment by Taramur** [comment]
Sadly it doesn't work. My plugin is strange anyway. Have to reconnect every time I start Galaxy. Is there a cache? Galaxy shows me online PSN Users, although I always have to reconnect the plugin. 
It's pulling my trophies of the missing games, but doesn't show them. 

[plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/6144652/plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log)

**Comment by FriendsOfGalaxy** [comment]
> Bloodborne

it is returned by the plugin as owned game

> Shadow of the Tomb Raider, Marvel Spider Man - those are not present in gamelist API, but present in trophy list.

Because you own them on disks only checking for trophies may be the only way to list them. See this topic for details: https://github.com/FriendsOfGalaxy/galaxy-integration-psn/issues/1#issuecomment-522445147

> Digital, not disk: Dark Souls Remastered

no signs. Is it on ps4 and have trophies?

> Have to reconnect every time I start Galaxy. Is there a cache? Galaxy shows me online PSN Users, although I always have to reconnect the plugin.

There is an issue in Galaxy: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/106
probably your case

**Comment by FriendsOfGalaxy** [comment]
Note for myself based on #23

Problem - user owns bundle of 3 games.

PSN gamelist API shows only one of them: `Metro Redux`, 
titleId: `CUSA00683_00`


Trophy titltes shows the rest two:
{"npCommunicationId":"NPWR06580_00","trophyTitleName":"Metro 2033 Redux
{"npCommunicationId":"NPWR06579_00","trophyTitleName":"Metro: Last Light Redux

grouped all user's games and trophytitltes (from his log file in #23):
[ShaunV gamelist and trophytitles.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/6663638/ShaunV.gamelist.and.trophytitles.zip)

**Comment by FriendsOfGalaxy** [comment]
Closing this issue as the fetching methods and authorization has changed in 0.34

It was already reported in #25 that a new version is missing some games as well, but let me prevent mixing technically different problems. Please report missing games issues separately
