### ISSUE TITLE
PSN Friends List no longer loads

### ISSUE THREAD

**Issue by ShaunV2** [FriendsOfGalaxy/galaxy-integration-psn#20]
I don't know when it started but no matter how long GoG Galaxy is open the friends list for PSN never loads now.
[logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/5877127/logs.zip)

**Comment by FriendsOfGalaxy** [comment]
Hey, do you mean friends presence on the right panel? In the logs I see that plugin is returning data properly. Maybe temporal problems with Galaxy backends?

**Comment by ShaunV2** [comment]
> Hey, do you mean friends presence on the right panel? In the logs I see that plugin is returning data properly. Maybe temporal problems with Galaxy backends?

Sorry I didn't get back to you right away, on first launch the friends list will not load, I have to exit and run it again for it to work, this includes Steam friends list and Xbox Live friends list as well, neither will load on first launch after turning the PC on.

**Comment by FriendsOfGalaxy** [comment]
OK, thanks for info. I've reported problem to Galaxy already, so let me close it here.
