### ISSUE TITLE
Access Denied when trying to login to PSN

### ISSUE THREAD

**Issue by ShaunV2** [FriendsOfGalaxy/galaxy-integration-psn#21]
This issue just started today, screenshot and logs provided:
![Screenshot (193)](https://user-images.githubusercontent.com/14097860/107592731-87bbee80-6bc2-11eb-95cf-fee9ad030c08.png)
[logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/5962611/logs.zip)
If you need other logs let me know.

**Comment by FriendsOfGalaxy** [comment]
It is not reproducing to me. Maybe temporal problems on sony end? 
![psndown](https://user-images.githubusercontent.com/48480506/107638438-e0959080-6c6f-11eb-965c-149168d58eae.png)

Could you retry?
