### ISSUE TITLE
PS Plus games are displayed even when the box is unchecked

### ISSUE THREAD

**Issue by philou-felin** [FriendsOfGalaxy/galaxy-integration-psn#22]
**Describe the bug**
All my PS4 games, including those from PS Plus are displayed as ""license_info": {"license_type": "SinglePurchase"}}", meaning they are displayed with the games I own. I noticed there's a toggle to disable "PS Plus" games, but it doesn't seem to work.

**Attached logs**
[plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/6112358/plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log)
(I tried to erase personal info.

**Comment by philou-felin** [comment]
Thanks for the explanation! I'll use GOG Galaxy 2.0's built-in "Hide" feature to hide the titles I don't like in the meantime. :)

**Comment by FriendsOfGalaxy** [comment]
ok, I'm glad to help
