### ISSUE TITLE
Trophies from several games on PS4 not shown in Galaxy despite delivered by the plugin

### ISSUE THREAD

**Issue by ShaunV2** [FriendsOfGalaxy/galaxy-integration-psn#23]
Final Fantasy Crystal Chronicles Remastered Edition (also missing artwork and all information about it)
Genshin Impact
The Legend of Heroes: Trails of Cold Steel IV (I already mentioned about this one before but nothing has been done about it and the game came out on PS4 last year)
Ys IX: Monstrum Nox
All of these games show up on [PSNProfiles](https://psnprofiles.com/MegaManZXAvent) just fine.

Let me know if you need any logs and which ones and I'll upload them.

**Comment by FriendsOfGalaxy** [comment]
@ShaunV2 thanks for report - standard plugin logs described in wiki should be enough. I need to verify if those games are recognized by the plugin as owned for the first place.

**Comment by ShaunV2** [comment]
I don't know which PSN logs you need so I just combined them all in a zip file.  The plugin does show I own the games as they show up but not the trophy data.
[logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/6380286/logs.zip)

**Comment by FriendsOfGalaxy** [comment]
Thanks.

Achievements send to Galaxy by the plugin conforms with your PSN profile for games you've listed above.

Eg. for `The Legend of Heroes: Trails of Cold Steel IV` plugin sends:

```
method=game_achievements_import_success, params={'game_id': 'CUSA19637_00', 'unlocked_achievements': [Achievement(unlock_time=1605007845, achievement_id='NPWR21068_00_1', achievement_name='The Magnificent Class VII'), Achievement(unlock_time=1605052775, achievement_id='NPWR21068_00_15', achievement_name='Raiders of the Lost Arts'), Achievement(unlock_time=1605060368, achievement_id='NPWR21068_00_18', achievement_name='Heavenly Jewel'), Achievement(unlock_time=1604378851, achievement_id='NPWR21068_00_19', achievement_name='Clashing Steel'), Achievement(unlock_time=1604903061, achievement_id='NPWR21068_00_21', achievement_name='The Early Bird Gets the Win'), Achievement(unlock_time=1604583512, achievement_id='NPWR21068_00_22', achievement_name='Hit the S-Breaks'), Achievement(unlock_time=1604312331, achievement_id='NPWR21068_00_23', achievement_name='Master Strategist'), Achievement(unlock_time=1604727484, achievement_id='NPWR21068_00_24', achievement_name='All Broken Up About It'), Achievement(unlock_time=1605008416, achievement_id='NPWR21068_00_25', achievement_name='Unbreakable Bonds'), Achievement(unlock_time=1604741715, achievement_id='NPWR21068_00_26', achievement_name='Tag-team Trouncing'), Achievement(unlock_time=1604581414, achievement_id='NPWR21068_00_27', achievement_name='Dynamic Duo'), Achievement(unlock_time=1605060997, achievement_id='NPWR21068_00_28', achievement_name='Teamwork Makes the Fiends Hurt'), Achievement(unlock_time=1604995187, achievement_id='NPWR21068_00_29', achievement_name='Order Up'), Achievement(unlock_time=1604390962, achievement_id='NPWR21068_00_30', achievement_name='Extra Special Operations'), Achievement(unlock_time=1604990574, achievement_id='NPWR21068_00_34', achievement_name='Orbal Beau'), Achievement(unlock_time=1604290854, achievement_id='NPWR21068_00_44', achievement_name='Joint Operation'), Achievement(unlock_time=1604303560, achievement_id='NPWR21068_00_45', achievement_name='Nightfall'), Achievement(unlock_time=1604459879, achievement_id='NPWR21068_00_46', achievement_name='The Trials of Class VII'), Achievement(unlock_time=1604477947, achievement_id='NPWR21068_00_47', achievement_name='A Shattered Blade'), Achievement(unlock_time=1604641160, achievement_id='NPWR21068_00_48', achievement_name='Guiding Starlight'), Achievement(unlock_time=1604974001, achievement_id='NPWR21068_00_49', achievement_name='Seekers of the Dawn'), Achievement(unlock_time=1604990575, achievement_id='NPWR21068_00_50', achievement_name='Night of Promises'), Achievement(unlock_time=1605091585, achievement_id='NPWR21068_00_51', achievement_name='Scattered Petals, Dying Flames'), Achievement(unlock_time=1605096712, achievement_id='NPWR21068_00_52', achievement_name='A New Dawn')]
```
BTW you have 0 unlocked trophies for `Genshin Impact`.

If you do not see it in Galaxy, then I guess it is Galaxy problem.

**Comment by FriendsOfGalaxy** [comment]
@ShaunV2 could you please upload GalaxyClient.log (all of them)? Maybe something interesting is here to prepare more precise problem report for GOG

**Comment by ShaunV2** [comment]
Here you go.
[Logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/6383049/Logs.zip)

**Comment by ShaunV2** [comment]
Any new information on this issue?  Still not fixed as the 4 games I mentioned still are claiming they have no trophies and you don't need to earn any for them to show up.

Also another issue:
GOG Galaxy is not pulling the friends list correctly on PSN, Steam and Xbox Live and even when it does it doesn't update the friends list in real time thus once it loads the friends list they're stuck like that and are never updated (I've seen it list like 7 or so friends online on PSN when in fact only two are online), I'm also having to restart the client multiple times for it to load the friends list for PSN, Steam and Xbox Live.

**Comment by FriendsOfGalaxy** [comment]
@ShaunV2 I recommend to send multiple reports via GOG Galaxy Report Problem tool (each for separate issue).

They usually quicker react on only most often reported problems.

**Comment by ShaunV2** [comment]
> @ShaunV2 I recommend to send multiple reports via GOG Galaxy Report Problem tool (each for separate issue).
> 
> They usually quicker react on only most often reported problems.

That did absolutely nothing, I reported the issues in two reports but they have done nothing about it also I noticed this plugin isn't picking up one of the games I own and have trophies to, Metro 2033 Last Light Redux which is part of a bundle but the plugin isn't picking up I own it at all.
Link to my PSN Profiles account showing I own it:
https://psnprofiles.com/trophies/2825-metro-last-light-redux/MegaManZXAvent

**Comment by ShaunV2** [comment]
> @ShaunV2 Pulling PS3 and PS VITA games is my saved task for future, then don't worry :)
> 
> Could you send me all your logs (the most important are from Galaxy client and PSN) especially from period when you are sure that Metro 2033 Last Light Redux should be?

Are you not able to look through the logs I already sent you?  I last earned trophies in Metro 2033: Last Light Redux back in 2017, it should've showed up in those logs already.  I only recently realized the plugin wasn't picking up I own it even though it was bought as a bundle as in it's both games in one download but separate trophy lists of course.

**Comment by tyrirn** [comment]
I also have a few games that are missing the trophies:
- NieR Replicant ver.1.22474487139...
- Little Nightmares II
- Crash Bandicoot 4: It's About Time

They show up fine here: https://psnprofiles.com/tyrirn
[plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/6611101/plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log)

**Comment by FriendsOfGalaxy** [comment]
@ShaunV2
> PSNProfiles can pull PS3 games then I don't see why the plugin can't.

I don't know their bussines operation mode but PSNProfiles specialize in PSN, and I maintains many plugins. Also - if they keep their code open source - I could check how they do that, but they keep it secret. They also probably have setup some background services with bot that parse PSN unpublic data. That costs.

Yes, I was able to find Metro 2033 Redux and also LastLight Redux in you logs.
```
{"npCommunicationId":"NPWR06580_00","trophyTitleName":"Metro 2033 Redux
{"npCommunicationId":"NPWR06579_00","trophyTitleName":"Metro: Last Light Redux
```

The case here is that we have `npCommunicationId` but don't have `npTitleId`. In other words this game does not come from owned games endpoint, only from trophies endpoint. This applies for issue #1 but maybe it is not only about PS4. Do you own their PS4 copy for those games or not? Maybe on disc?

If you want to help, please try to keep one issue per one problem. Creating buzz "this and that does not work" in one issue is unhelpful.

>  I don't even know how to look the reports up after submitting them, there is no way that I know of to get to that page through the client.

you should be able to find them on your account in https://mantis2.gog.com/

@tyrirn I can confirm that plugin send notifications with achievements for those games:
- NieR Replicant ver.1.22474487139...
- Little Nightmares II

Crash Bandicoot 4: It's About Time is similar case as Metro 2033 Redux. Do you own this game on disc or digital copy? Is it for PS4?

**Comment by ShaunV2** [comment]
I own both as a digital copy on PS4 and they are sold as a bundle on the PS Store, digital or physical shouldn't matter at all.

**Comment by tyrirn** [comment]
So for those two games it's a GoG Galaxy issue? And I own a digital copy of 'Crash Bandicoot 4: It's About Time' bought from the PSN store. In my PSN library it is shown two times, one with PS4 label and one with PS5 label. In my PSN Trophies tab, it's only the PS4 one with trophies unlocked as i don't own a PS5 yet.

**Comment by FriendsOfGalaxy** [comment]
@ShaunV2 by bundle do you mean this https://store.playstation.com/en-us/product/UP2047-CUSA11408_00-METROSAGABUNDLE0 ?

@tyrirn 
> So for those two games it's a GoG Galaxy issue?

yes, it is Galaxy issue.

> And I own a digital copy of 'Crash Bandicoot 4: It's About Time'

this one https://store.playstation.com/en-us/product/UP0002-PPSA02432_00-CB4THEGAME000001 ? Or from any other region? It sometimes matter. I need to buy exactly the same to investigate more.

**Comment by tyrirn** [comment]
I own a digital copy of this: https://store.playstation.com/en-ro/product/EP0002-PPSA02433_00-CB4THEGAME000001

**Comment by ShaunV2** [comment]
> @ShaunV2 by bundle do you mean this https://store.playstation.com/en-us/product/UP2047-CUSA11408_00-METROSAGABUNDLE0 ?

No that is not the correct bundle at all, what I have only comes with 2 games not 3, the 3rd game wasn't out when I bought the bundle of only:
Metro 2033 Redux
Metro 2033: Last Light Redux
