### ISSUE TITLE
I can not enable integration with the store

### ISSUE THREAD

**Issue by DrDosvidoni** [FriendsOfGalaxy/galaxy-integration-psn#27]
I can not enable integration with the store
sony
{"error_code":4151,"error":"unauthorized_client","error_description":"Client does not have grant type: [\"implicit\",\"authorization_code\"]","docs":"http://central-auth.p1-np-eib.prod.navcloud.sonynei.net/docs/#api/centralauthservice/v1/oauth/authorize/get"}

**Comment by kyuuketsukikurai** [comment]
Same issue here. Was previously working, but now it won't connect.

**Comment by tyrirn** [comment]
Same, here, any chance we get this back?

**Comment by balambuc** [comment]
FYI:

https://github.com/FriendsOfGalaxy/galaxy-integration-psn/issues/25#issuecomment-883199020

**Comment by FriendsOfGalaxy** [comment]
Closing as duplicate
