### ISSUE TITLE
Disc based games no longer being detected/shown.

### ISSUE THREAD

**Issue by ScarletWagon** [FriendsOfGalaxy/galaxy-integration-psn#33]
The played games section of myplaystaion is no longer being shown in Gog. I noticed this when The last of us 2 which i own on disc no longer showed up. It only show the digitally purchased games.
Link to what I'm refering to: https://library.playstation.com/recently-played

**Comment by FriendsOfGalaxy** [comment]
Well, this could be returned as owned based on recently played or unlocked achievements. Accepting PRs
