### ISSUE TITLE
The Integration always shows as offline is GOG Galaxy 2.0 

### ISSUE THREAD

**Issue by egImmortal** [FriendsOfGalaxy/galaxy-integration-psn#34]

**Comment by egImmortal** [comment]
Like it signs me in and it shows as offline

**Comment by FriendsOfGalaxy** [comment]
Can't do much without logs. Try again with issue template https://github.com/FriendsOfGalaxy/galaxy-integration-psn/issues/new?assignees=&labels=&template=bug_report.md&title=
