### ISSUE TITLE
`invalid_client` error when trying to connect account

### ISSUE THREAD

**Issue by tanelso2** [FriendsOfGalaxy/galaxy-integration-psn#35]
**Describe the bug**
When in the GOG Galaxy Settings menu, I try to enable the PSN plugin and connect my account. Instead of a login screen, I am presented with a JSON error

```
{"error_code":4173,"error":"invalid_client","error_description":"Invalid client","docs":"http://central-auth.p1-np-eib.prod.navcloud.sonynei.net/docs/#api/centralauthservice/v1/oauth/authorize/get"}
```

**Attached logs**
[plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log](https://github.com/FriendsOfGalaxy/galaxy-integration-psn/files/7306899/plugin-psn-38087aea-3c30-439f-867d-ddf9fae8fe6f.log)

**Comment by MattLloyd101** [comment]
This appears to be an issue with the integration not updating.

My recommendation is to navigate to the Lookup directory, and remove the psn_ prefixed directory. Restart GOG & try the integration again.

**Lookup directory**

Windows:
`%localappdata%\GOG.com\Galaxy\plugins\installed`

macOS:
`~/Library/Application Support/GOG.com/Galaxy/plugins/installed`

The previous version of the http_client.py provided a UUID as client ID, that for some reason was no longer registered, the latest code has been cleaned up to no longer need many of the scopes or an explicit client ID (amongst other things). As such it doesn't fail.

**Comment by tanelso2** [comment]
That worked! Thank you!
