### ISSUE TITLE
Games played on PS5 don't update

### ISSUE THREAD

**Issue by Dfox444** [FriendsOfGalaxy/galaxy-integration-psn#36]
Describe the bug:
Basically an example I first noticed is when I first got GOG, it shows I played Kingdom Hearts 3 last 2 years ago and that was on my PS4, I started playing it again on my PS5 more recently and it hasn't updated anything. It does show I own the games. I played other games like Tales of Arise and Life is Strange True Colors and they say I own it but no game time is put into it even if I resync or disconnect from PSN and such. It also doesn't display any trophies I got from games played on PS5 either.

To Reproduce:
1. Play a game on PS4 then check GOG for any updates
2. Play the same game on PS5 then check GOG if anything changed

Expected Behaviour:
It should just update normally like any other game. I know it updates stuff as I play Genshin Impact on PC and it always displays my game time but it doesn't update it if I play it on PS5 either.

**Comment by FriendsOfGalaxy** [comment]
The reason is that we lost last-played feature some time ago. Issue to re-add it is here: #28 
Closing as duplicate then
